apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ printf "%s-%s" .Values.spec.efsVolumeClaim .Values.spec.env }}"
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.spec.storageClassName }}
  resources:
    requests:
      storage: 10Gi
