apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.spec.efsVolumeClaim }}
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.spec.storageClassName }}
  resources:
    requests:
      storage: 20Gi
